# Generated by Django 3.0.5 on 2020-06-27 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0002_feed_photo'),
        ('feedpage', '0006_feed_photo'),
    ]

    operations = [
    ]
